# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# Use GitHub Actions CI to verify successful Gradle builds on:
# - Java 8 (LTS)
# - Java 11 (LTS)
# - Java 15 (deprecated)
# - Java 16 (current, until September 2021)
name: CS321 Bioinformatics CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11', '15', '16' ]
    name: Java version ${{ matrix.Java }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        # the distribution can be either 'adopt' or 'zulu'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

      # Skip running tests, as this startup code intentionally
      # contains failing tests that are used as templates.
      #
      # For your team, you can enable running these tests
      # by uncommenting the next two lines
#    - name: Run all jUnit tests with Gradle
#      run: ./gradlew test
    - name: Create jar GeneBankCreateBTree with Gradle
      run: ./gradlew createJarGeneBankCreateBTree
    - name: Create jar GeneBankSearch with Gradle
      run: ./gradlew createJarGeneBankSearch
